# Generated by Django 6.0.5 on 2026-06-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('workplace', models.CharField(max_length=200, verbose_name='Current Factory / Workplace')),
                ('preferred_branch', models.CharField(choices=[('Nairobi HQ', 'Nairobi Headquarters (Kilome Rd)'), ('Eldoret', 'Eldoret Branch'), ('Other', 'Other Regional Branch')], default='Nairobi HQ', max_length=50)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description of Issue')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Membership Inquiry',
                'verbose_name_plural': 'Membership Inquiries',
            },
        ),
    ]
