# Generated by Django 6.0.5 on 2026-06-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('union_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('national_id', models.CharField(max_length=50, unique=True, verbose_name='National ID / Passport Number')),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('current_workplace', models.CharField(max_length=200, verbose_name='Current Factory / Employer')),
                ('job_title', models.CharField(help_text='e.g., Machine Operator, Packer', max_length=100)),
                ('date_employed', models.DateField(verbose_name='Employment Start Date')),
                ('assigned_branch', models.CharField(choices=[('Nairobi HQ', 'Nairobi Headquarters (Kilome Rd)'), ('Eldoret', 'Eldoret Branch'), ('Mombasa', 'Mombasa Branch'), ('Kisumu', 'Kisumu Branch')], default='Nairobi HQ', max_length=50)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('membership_status', models.CharField(choices=[('pending', 'Pending Verification'), ('active', 'Active Member'), ('suspended', 'Suspended')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name': 'Union Member',
                'verbose_name_plural': 'Union Members',
            },
        ),
        migrations.CreateModel(
            name='WorkplaceIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(max_length=150, verbose_name='Worker Full Name')),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_name', models.CharField(max_length=200, verbose_name='Employer/Company Name')),
                ('issue_category', models.CharField(choices=[('wages', 'Unpaid Wages / Underpayment'), ('dismissal', 'Unfair Dismissal / Termination'), ('safety', 'Occupational Safety/Health Hazard'), ('harassment', 'Workplace Harassment / Discrimination'), ('other', 'Other Labor Grievance')], default='wages', max_length=100)),
                ('incident_date', models.DateField(blank=True, null=True, verbose_name='Date of Incident')),
                ('details', models.TextField(verbose_name='Detailed Description of the Issue')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Mark as Resolved')),
            ],
            options={
                'verbose_name': 'Workplace Issue',
                'verbose_name_plural': 'Workplace Issues',
            },
        ),
        migrations.DeleteModel(
            name='MembershipInquiry',
        ),
    ]
